### ISSUE TITLE
 keep nerve entities out of the entity panel until they are vetted

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-NERVEWrapper#3]
1. Open the letter sample
2. run NERVE
result:
![image](https://user-images.githubusercontent.com/6600070/55185909-fae92280-515a-11e9-98ae-30d32c6326a6.png)

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-WriterBase/commit/028c09e1e9289d5fafd4b6418b19246e1a64aaa1

**Comment by ilovan** [comment]
confirmed on dev-cwrc-writer
