### ISSUE TITLE
make NERVE ignore already existing entities

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-NERVEWrapper#4]
e.g. run NERVE on the sample letter template, which has several entities: 

![image](https://user-images.githubusercontent.com/6600070/55186031-3552bf80-515b-11e9-8bd6-80c21fae5243.png)

and also

![image](https://user-images.githubusercontent.com/6600070/55185986-266c0d00-515b-11e9-8830-4ce562645ad5.png)

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-WriterBase/commit/1c4112e6ebdd5e13a840eb0ff0cda8ca7a46539d

**Comment by ilovan** [comment]
confirmed on both production sites
