### ISSUE TITLE
make  "accept all matching" button available only on entities that have total matches (string, standard, URI)

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-NERVEWrapper#5]
1. Open template letter
2. run NERVE
result: 3 Oslo instances ( "accept all matching" button available on all three of them, as well as on any other NERVE entity, including unique ones like Copenhagen)
3. edit one of the Oslo instances to add linking
result:
![image](https://user-images.githubusercontent.com/6600070/55186442-2caeb900-515c-11e9-9f1f-1a4887bb3e55.png)

desired behaviour:
the first instance of Oslo should not have "accept all matching" available, as it does not match the other two anymore (the user could always still merge all three of them with the regular "Merge" action)

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-WriterBase/commit/6815c97826e61da850df47679764905fbceae0e9

**Comment by ilovan** [comment]
confirmed on dev-cwrc-writer
