### ISSUE TITLE
After accepting a merged entity, it still shows up with NERVE-true in the entities pannel in all the individual instances

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-NERVEWrapper#6]
same steps as in  #5 
+
Click on "Merge"
Merge the three Oslo instances
Go to the Entities panel
Click on any last 3 of the 4 Oslo entities

**Comment by ilovan** [comment]
OK, now  I get it, the entity gets rid of the nerve true property after the user finishes vetting the NERVE entities and hits "Done".

However, if we go with #3 , then the entities should pop up on the entity panel, with the correct details, as soon as they are accepted and disappear from the NERVE panel.

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-WriterBase/commit/028c09e1e9289d5fafd4b6418b19246e1a64aaa1

**Comment by ilovan** [comment]
confirmed on dev-cwrc-writer.cwrc.ca

**Comment by ilovan** [comment]
confirmed on both production sites
